[Advanced Operators] 構文を変更
stzn/the-swift-programming-language-jp pull request #309
Opened 2022-07-18 11:36 UTC by tsubasarc

読みやすくなるよう訳の文章に変更を施した
Fix stzn#301

Closes #301

2022-07-18 11:38 UTC, tsubasarc commented
元のままでも読みやすい過剰な変更がないか見直しますので、
もしかしたら force push あるかも知れないです。

2022-07-19 02:31 UTC, t-ae requested changes

2022-07-19 02:31 UTC, t-ae commented on language-guide/advanced-operators.md
> +負数に対するこの変換は、2 の_補数表現_と呼ばれています。負数を表すのに珍しい方法に見えるかもしれませんが、いくつかの利点があります。
```suggestion
負数に対するこの符号化法は、2 の_補数表現_と呼ばれています。負数を表すのに珍しい方法に見えるかもしれませんが、いくつかの利点があります。
```

`encoding` を`エンコーディング`とせず日本語にするなら、`符号化法`か`表現法`あたりが良いと思います。

2022-07-19 02:31 UTC, t-ae commented on language-guide/advanced-operators.md
> +また、2 の補数表現は負数のビットを正数のように左右にシフトできます。左にシフトするたびにビットを 2 倍し、右にシフトするたびにビットを半分にします。これを実現するために、符号付き整数の右シフトでは追加の規則が適用されます。符号付き整数を右にシフトするとき、符号なし整数と同じ規則を適用しますが、空いた左のビットすべてを 0 ではなく符号ビットで埋めます。
```suggestion
また、2 の補数表現は負数のビットを正数のように左右にシフトできます。左にシフトするたびに数値を 2 倍し、右にシフトするたびに数値を半分にします。これを実現するために、符号付き整数の右シフトでは追加の規則が適用されます。符号付き整数を右にシフトするとき、符号なし整数と同じ規則を適用しますが、空いた左のビットすべてを 0 ではなく符号ビットで埋めます。
```

`them` は `negative numbers`にかかるはずです。

2022-07-19 20:19 UTC, stzn commented on language-guide/advanced-operators.md
> +ただし、負数は別の方法で格納されます。それらは `2` と `n` のべき乗から絶対値を引くことによって格納されます。ここで言う `n` は符号ビットを除いたビット値の桁です。8 ビットの数値には 7 つのビット数があるため、これは 2 の 7 乗、つまり `128` です。
>数値をバックティックで囲うか

ここは原文でspanを使って強調されていた部分にバックティックを使っています。他の言語の翻訳でもそのようにしていますので、それに合わせました。なので 2 の 7 乗に付いていない方がミスだと思います。

> 数値をバックティックで囲うかどうかのルールがCONTRIBUTION.mdに見当たりません

そうですね。原文でspanなどで強調されているものに関してはバックティックを使うなどの記載はあった方が良さそうですね。ありがとうございます。

2022-07-19 21:12 UTC, tsubasarc commented
レビューでもらった提案を共著コミットし、それをローカルにも rebase したのですが、これって force push しても大丈夫なのでしょうか？

2022-07-20 00:29 UTC, tsubasarc commented
レビュー、ありがとうございます 🙏🏽 

色々と機能の使い方を間違えましたが、
なんとか形にはなったと思います 🙇🏽

2022-07-20 00:32 UTC, t-ae commented
コメントがOutdatedで隠れてしまったので再掲します。

> 値ビット(value bits)は符号ビット(sign bit) に対応するものなので、翻訳としても対応関係がわかりやすいように値ビットのままのほうが良いのではないかと思います。
> この文中(https://github.com/stzn/the-swift-programming-language-jp/pull/309/files#diff-1b280fa945bbfb41d1359c6bb8b295d01c9e958b36a01b6f57c65edfb8068e5eR141) だと7つのビット数という所が分かりづらくなっており、7つの値ビットのほうが明確です。
> 値ビットという語自体は少し上で定義されており、これを使わない理由はないと思います。

2022-07-20 00:40 UTC, tsubasarc commented
@t-ae 
すみません、やったつもりになってました… 💦

2022-07-21 00:27 UTC, t-ae commented on language-guide/advanced-operators.md
> +今回は、符号ビットは `1`\(「負」を意味する\)で、7 つのビット値は `124` の 2 進数値\(`128 - 4`\)です:
```suggestion
今回は、符号ビットは `1`\(「負」を意味する\)で、7 つの値ビットは `124` の 2 進数値\(`128 - 4`\)です:
```

2022-07-21 00:58 UTC, t-ae commented on language-guide/advanced-operators.md
> +ただし、負数は別の方法で格納されます。それらは `2` の `n` 乗から絶対値を引くことによって格納されます。ここで言う `n` は符号ビットを除いたビット値の桁数です。8 ビットの数値には 7 つの値ビットがあるため、これは `2` の `7` 乗、つまり `128` です。
```suggestion
ただし、負数は別の方法で格納されます。それらは `2` の `n` 乗から絶対値を引くことによって格納されます。ここで言う `n` は値ビットの数です。8 ビットの数値には 7 つの値ビットがあるため、これは `2` の `7` 乗、つまり `128` です。
```

値ビット＝符号ビットを除いたビット値という定義があり、原文でも`value bits`なので、ここは値ビットを用いるのが良いと思います。

2022-07-21 14:46 UTC, t-ae approved these changes

2022-07-21 18:48 UTC, stzn reviewed
ありがとうございます!いくつかコメントさせていただきましたmm

2022-07-21 18:48 UTC, stzn commented on language-guide/advanced-operators.md
> +下記の例にある `someBits` と `moreBits` は、異なるビットに `1` を設定されています。ビット論理和演算子はそれらを組み合わせて、符号なし 10 進数の `254` に相当するビット値 `11111110` を作成します。
文脈的に「が」の方が自然かなと思いました。

```suggestion
下記の例にある `someBits` と `moreBits` は、異なるビットに `1` が設定されています。ビット論理和演算子はそれらを組み合わせて、符号なし 10 進数の `254` に相当するビット値 `11111110` を作成します。
```

2022-07-21 18:48 UTC, stzn commented on language-guide/advanced-operators.md
> +ビット排他的論理和演算子\(`^`\)は、2 つのビット値を比較します。入力されたビット値において、いずれもビットが異なる場合は `1` を、等しい場合は `0` が設定されたビット値を新たに返します:
ここの「を」は次の文との繋がり的にいらないかなあと思いました。

```suggestion
ビット排他的論理和演算子\(`^`\)は、2 つのビット値を比較します。入力されたビット値において、いずれもビットが異なる場合は `1` 、等しい場合は `0` が設定されたビット値を新たに返します:
```

2022-07-21 18:48 UTC, stzn commented on language-guide/advanced-operators.md
> +下記の例にある `firstBits` と `otherBits` のビットは、一方が持たない `1` を互いに設定されています。ビット排他的論理和演算子は、これらに `1` を設定した新しいビット値を出力します。`firstBits` および `otherBits` が持つ他のビットはすべて一致しているので、それらは `0` に設定されます。
全般の話になってしまいますが、能動態と受動態の表現は統一されていた方が良いかなあと思い、「〇〇が設定された」という表現に合わせてみました。(そもそも混ぜた僕がいけないですw)


```suggestion
下記の例にある `firstBits` と `otherBits` のビットは、一方が持たない `1` が互いに設定されています。ビット排他的論理和演算子は、これらに `1` が設定された新しいビット値を出力します。`firstBits` および `otherBits` が持つ他のビットはすべて一致しているので、それらは `0` が設定されます。
```

2022-07-22 00:06 UTC, tsubasarc commented
@stzn @t-ae 
ありがとうございます 🙏🏽

2022-07-22 00:46 UTC, stzn approved these changes

2022-07-24 00:39 UTC, merged