[A Swift Tour] 新規文章の追加、翻訳の改善
stzn/the-swift-programming-language-jp pull request #315
Opened 2022-07-21 08:01 UTC by t-ae

- Concurrencyがなかったので追加
- `if let`の同名省略の記述を追加(Swift5.7からなのでコメントアウトしています)
- その他翻訳の改善

判断に迷う箇所はコメントしていきます。

2022-07-21 08:08 UTC, t-ae commented on welcome-to-swift/a-swift-tour.md
> +<!-- Swift 5.7で追加
現在の所Swift5.6を対象としているようだったので、とりあえずコメントアウトした状態で追加しました。

2022-07-21 08:08 UTC, t-ae commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースのインスタンスのそれぞれは、常に同じ Raw Value を持つということです。列挙ケースが関連値を持つもう 1 つの方法があります。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated Valu
`If an enumeration has raw values, those values are determined as part of the declaration, which means every instance of a particular enumeration case always has the same raw value.`

enumの各ケースの実体(インスタンス)に割り当てられたRaw Valueは不変であるということだと思うが、日本語訳が難しい。

`You can think of the associated values as behaving like stored properties of the enumeration case instance.` はまるっと抜けていた(後から追加された？)ので追加しました。

2022-07-21 10:30 UTC, tsubasarc commented
元のままでも意味はわかるんですが、この文で 全て を それぞれ にしたい場合、各 を使うと引っ掛かりなく読める訳になるんじゃないかなぁと。

2022-07-21 11:19 UTC, t-ae commented
@tsubasarc 
> 元のままでも意味はわかるんですが、この文で 全て を それぞれ にしたい場合、各 を使うと引っ掛かりなく読める訳になるんじゃないかなぁと。

ここ自分の誤解が原因で元の文が変だと思って変更してしまっていました。
`特定の列挙ケースの全てのインスタンス` だと一つの列挙ケースにたくさんインスタンスがあるということになり、それは変じゃないかと思ったのですが、Swiftの列挙体は値型なので、別の変数に代入すればそれは異なるインスタンスになるのでした。ここは元の文に戻しておきます。

> それと、Another choice for enumeration cases is to have values associated with the case の日本語訳がちょっと違うと感じたのでレビューしてみました。

レビューコメントが見えていないのですが投稿できているでしょうか？
Suggestion送っていただければ共著コミットにします。

2022-07-21 11:24 UTC, tsubasarc commented
@t-ae 
そうだったんですね。分かりました！

> レビューコメントが見えていないのですが投稿できているでしょうか？

すみません、レビューという言い方が間違ってました。
たぶん、レビュアーにアサインされていない僕は suggestion できないと思うので、さっきのはコメントとして考えを書いてみた次第です。

2022-07-21 11:28 UTC, t-ae commented
あれ？できないですか？
私は #309 で横からsuggestion出しているのでできないことはないと思いますが…
設定上私からレビュー依頼を出すことはできないようです。

2022-07-21 11:35 UTC, tsubasarc commented
@t-ae ごめんなさい！
出来るにはできるのですが、アサインされてないのでロール違うかなという気持ちから出た言い方でした…。

Suggestion しますね。

2022-07-21 11:40 UTC, stzn commented
今、お二人Collaboratorに入れてみたのですが、これでreviewerに追加できるようなりますでしょうか？

2022-07-21 11:40 UTC, stzn commented on welcome-to-swift/a-swift-tour.md
> +<!-- Swift 5.7で追加
原文に入っているのでそのまま追加していただいて大丈夫です🙆🏻‍♂️

2022-07-21 11:42 UTC, tsubasarc requested changes
翻訳文を改善

2022-07-21 11:42 UTC, t-ae commented
@stzn
Reviewersの設定ボタンは出たのですが @stzn さんしか一覧に出ませんね。
assigneesのほうも設定ボタンが出て、こちらは @tsubasarc さんも設定できるようです。

2022-07-21 11:43 UTC, stzn commented
@t-ae さん
ありがとうございますmm方法調べてみます。

2022-07-21 11:45 UTC, tsubasarc commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースのインスタンスのそれぞれは、常に同じ Raw Value を持つということです。列挙ケースが関連値を持つもう 1 つの方法があります。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated Valu
すみません、何か間違えてますね。
やり直します。

2022-07-21 11:51 UTC, tsubasarc requested changes
翻訳文を改善

2022-07-21 11:51 UTC, tsubasarc commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。列挙ケースが関連値を持つもう 1 つの方法があります。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated Value\
もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値(Associated Value)は列挙ケースのインスタンスの格納プロパティのように振る舞います。例えば、サーバから日の出時刻と日の入り時刻をリクエストする場合を考えてみてください。サーバはリクエスト情報に応じたレスポンスを返すか、リクエストが間違っている場合は間違っているという内容を返します。

2022-07-21 11:54 UTC, tsubasarc commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。列挙ケースが関連値を持つもう 1 つの方法があります。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated Value\
やり方がわからず間違ってるみたいです。
すみませんが、 今回は @t-ae さんだけで修正コミットお願いします 😭

2022-07-21 11:58 UTC, t-ae commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。列挙ケースが関連値を持つもう 1 つの方法があります。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated Value\
変更したい行でコメントフォームを開き、`Cmd+g`(Add a suggestionボタン)でその行の内容がsuggestionに囲われた状態で入力されるので、その内容を修正するとできます。

2022-07-21 12:25 UTC, tsubasarc requested changes
翻訳文を改善

2022-07-21 12:25 UTC, tsubasarc commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。列挙ケースが関連値を持つもう 1 つの方法があります。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated Value\
```suggestion
もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値(Associated Value)は列挙ケースのインスタンスの格納プロパティのように振る舞います。例えば、サーバから日の出時刻と日の入り時刻をリクエストする場合を考えてみてください。サーバはリクエスト情報に応じたレスポンスを返すか、リクエストが間違っている場合は間違っているという内容を返します。
```

2022-07-21 12:43 UTC, t-ae commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated V
```suggestion
もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値 Associated Value を持たせることです。Associated Value はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。Associated Value は列挙ケースのインスタンスの格納プロパティのように振る舞います。例えば、サーバから日の出時刻と日の入り時刻をリクエストする場合を考えてみてください。サーバはリクエスト情報に応じたレスポンスを返すか、リクエストが間違っている場合は間違っているという内容を返します。
```

`もう一つの選択肢は、` から Associated Valueの話が始まりますが、原文だと用語としてのassociated valueが無く、日本語訳すると指示語が読みにくさを助長してしまいます。
原文から離ることになりますが、最初に Associated Value の説明をもってきて、以降はそれを使う方が読みやすいかと思うのですが、どうでしょうか。

2022-07-21 14:54 UTC, tsubasarc commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated V
僕もこれ意識してました。
定義が先にあると、とても読みやすいと思うので僕は賛成です！

@stzn さん、どうでしょうか？

2022-07-21 18:32 UTC, stzn commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated V
はい、僕も賛成です🙂最初に「そもそもこれ何だっけ？」というのをはっきりさせた方が読んでいる側も読みやすくなると思いました。

2022-07-21 19:10 UTC, stzn reviewed
ありがとうございます!すごいわかりやすくなったように感じます🙂
いくつかコメントさせていただきましたmm

2022-07-21 19:10 UTC, stzn commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated V
Raw Valueについて全部の値が等しいみたいな印象を受けるので同じ型という方が良いかなあと思いました。

関連値は初出だと思うので、それっぽい表現があった方が良いかなあと個人的に思いました。

```suggestion
もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ型の Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらは関連値\(Associated Value\)と呼ばれ、列挙ケースのインスタンスの格納プロパティのように振る舞います。例えば、サーバから日の出時刻と日の入り時刻をリクエストする場合を考えてみてください。サーバはリクエスト情報に応じたレスポンスを返すか、リクエストが間違っている場合は間違っているという内容を返します。
```

2022-07-21 19:10 UTC, stzn commented on welcome-to-swift/a-swift-tour.md
> +非同期関数の呼び出す際には、その前に `await` を付けます。
```suggestion
非同期関数を呼び出す際には、その前に `await` を付けます。
```

2022-07-21 19:10 UTC, stzn commented on welcome-to-swift/a-swift-tour.md
> +既存の型に新しい機能\(メソッドや計算プロパティ\)を追加する場合に、`extension` を使います。他のファイルやモジュールで宣言された型やライブラリやフレームワークからインポートした型にプロトコルを準拠させる場合にも `extension` を使います。
区切りがあった方が読みやすいかなあと思いました。

```suggestion
既存の型に新しい機能\(メソッドや計算プロパティ\)を追加する場合に、`extension` を使います。他のファイルやモジュールで宣言された型や、ライブラリやフレームワークからインポートした型にプロトコルを準拠させる場合にも `extension` を使います。
```

2022-07-21 20:49 UTC, tsubasarc commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated V
@stzn ありがとうございます！

2022-07-21 21:11 UTC, tsubasarc commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated V
#### 先例

https://github.com/stzn/the-swift-programming-language-jp/blob/e21aada266de0b57deabf728a0add585e2bfc57b/language-guide/enumerations.md?plain=1#L130

2022-07-21 21:22 UTC, tsubasarc commented
遅れましたが、Collaborator への invitation ありがとうございます 🙇🏽

2022-07-21 21:29 UTC, stzn commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated V
あーすいません。先例があったんですね。そうしましたら、そのままで大丈夫です。

> すると Raw Value の方も漢字のやつで訳が欲しくなりませんか…？

そうですね。Appleが公表している内容の中で適切なワードが見つかればそれを使いたいです(今は見つかっていない場合は英語表記のままというルールに沿っています)

2022-07-22 00:37 UTC, t-ae commented on welcome-to-swift/a-swift-tour.md
> +サブクラスは、そのクラス名の後に、スーパークラスの名前をコロン\(`:`\)で区切って指定します。標準で定義されているルートクラスのサブクラスにする必要はありませんので、必要に応じて指定も省略もできます。
私もここは妙だなと思っていました。
ご提案のほうが分かりやすいので使わせていただきます。

2022-07-22 00:49 UTC, t-ae commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated V
関連値は個別ドキュメントのほうで先例あったんですね… Raw Value に合わせて Associated Value にしていました。

> Raw Valueについて全部の値が等しいみたいな印象を受けるので同じ型という方が良いかなあと思いました。

多分私がしていた誤解と同じ誤解をされていると思うのですが、ここで書かれている `全てのインスタンス` というのはケース自体ではなくケースを代入して作られた実体を指し示しているという認識です。

```swift
enum Enum: Int { case case1, case 2}
let c1_1 = Enum.case1
let c1_2 = Enum.case1
let c2 = Enum.case2
```

enumは値型なので`c1_1`と`c1_2`は別のインスタンスとなりますが、これらは同じ Raw Value を持っています。
`c2` も同じ型の Raw Value を持っていますが、これは別のケースのインスタンスなので違う値になります。

この例だと、原文の `every instance of a particular enumeration case` は `c1_1`と `c1_2` のことを指すことになると自然だと思いますがどうでしょうか。

2022-07-22 02:20 UTC, t-ae commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースのインスタンスのそれぞれは、常に同じ Raw Value を持つということです。列挙ケースが関連値を持つもう 1 つの方法があります。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated Valu
他所で修正されたのでResolveしておきます。

2022-07-22 10:26 UTC, stzn commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated V
そうですね！おっしゃる通りだと思います(すいません自分で書いておきながら...w)。suggestは気にしないでくださいmm

2022-07-22 10:40 UTC, stzn commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう 1 つの選択肢は、列挙ケースに関連づいた値 Associated Value を持たせることです。Associated Value はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異な
すいません僕の説明の仕方が良くなかったです。関連値に関しては訳が決まっているので、初出時だけ「関連値\(Associated Values\)」として残りは関連値として欲しかったです🙇🏻‍♂️(変ですかね...？)

```suggestion
もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう 1 つの選択肢は、列挙ケースに関連値\(Associated Values\)を持たせることです。関連値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。関連値は列挙ケースのインスタンスの格納プロパティのように振る舞います。例えば、サーバから日の出時刻と日の入り時刻をリクエストする場合を考えてみてください。サーバはリクエスト情報に応じたレスポンスを返すか、リクエストが間違っている場合は間違っているという内容を返します。
```

2022-07-22 11:49 UTC, stzn commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated V
ちなみにRaw Valueですが、WWDCでは「Raw値」となっていましたが...どうなんでしょう😅

2022-07-22 14:17 UTC, t-ae commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated V
Raw値…実際使われてるのは見たことないですね。
公式翻訳を重視するのもいいですが、日本語コミュニティで広く使われている呼び方があるならそれを使うというのもありかなと思います。読者がコミュニティに流れてきたときに違和感なく溶け込めるので。

ところでREADME.mdによると

> なお、英語のまま表記の大文字、小文字は、原文の記載に従います。
> 
> 通常の英語と同様に文の開始は大文字、その他は小文字
> 例: 開始 -> Computed property、その他 -> computed property

とのことですが、Raw Valueでは守られていないようですね。
この文章はCONTRIBUTION.mdのほうに記載がないので、正規のルールならそちらに追加すべきかと思います。

2022-07-22 14:28 UTC, t-ae commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう 1 つの選択肢は、列挙ケースに関連づいた値 Associated Value を持たせることです。Associated Value はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異な
訳が決まっていたのでこれが良いですね。ありがとうございます。
Associated Values が複数形になっていますが、Raw Value が全体に単数形なので、そちらに合わせて単数形にしておきます。

2022-07-22 19:04 UTC, stzn commented on welcome-to-swift/a-swift-tour.md
> +もし列挙型が Raw Value を持つ場合、これらの値は宣言の一部として決定されます。これはつまり、特定の列挙ケースの全てのインスタンスは、必ず同じ Raw Value を持つということです。もう一つの選択肢は、列挙ケースに関連づいた値を持たせることです。それらの値はインスタンス生成時に決定され、列挙ケースのインスタンスごとに異なる値を持つことができます。これらの値\(Associated V
ありがとうございます!
このルール最近決まったので逆にそうなっていない所を修正したいと思ってました。なので、もし可能であれば一緒に直していただけると嬉しいですmm

2022-07-23 02:05 UTC, t-ae commented on welcome-to-swift/a-swift-tour.md
> +> `radius` と `name` をイニシャライザの引数に受けとる `Circle` という名前の `NameShape` の別のサブクラスを作ってみましょう。そして、 `Circle` クラスに `area()`、`simpleDescription()` メソッドを実装してみましょう。
原文ではバックティックのついていない箇所ですが、ここでは半径と名前を指すと同時に引数名を指定していると考えられます。
コードについての指定になるため、バックティックで囲うのが適切かと思い付けました。

2022-07-23 04:13 UTC, stzn approved these changes

2022-07-25 00:49 UTC, t-ae commented
@tsubasarc 
Approveして貰えればマージできる状態です。
subscriptの翻訳が残っていますが、これは後で他ファイル含め一括でやろうと思います。

2022-07-25 01:49 UTC, tsubasarc approved these changes

2022-07-25 01:54 UTC, tsubasarc commented
遅くなってすみません！
Approval しました。
次回からは気をつけます… 🙇🏽

2022-07-27 12:41 UTC, merged