typoの修正とdoneの翻訳変更
stzn/the-swift-programming-language-jp pull request #337
Opened 2022-08-09 02:48 UTC by t-ae

2022-08-09 02:49 UTC, t-ae commented on language-guide/advanced-operators.md
> +このコードは機能しますが、少し扱いづらく感じます。`AllCaps` の後の深くネストされた括弧は読みにくく、`name` が `nil` の場合に「World」を使用するフォールバックロジックは、`??` を使用してインラインで記述する必要があります。これは、より複雑なものに対しては困難です。描画の一部を構成するために `switch` または `for` ループを含める必要があっても、方法は
原文`The fallback logic to use “World” when name is nil has to be done inline using the ?? operator, `

`インラインで実行する` だと意味が通らないので `記述する` に変更しました。

2022-08-09 18:58 UTC, stzn commented on language-guide/advanced-operators.md
> +最終更新日: 2022/7/15
日付更新していただけると嬉しいです！

2022-08-10 01:43 UTC, t-ae commented on language-guide/advanced-operators.md
> +最終更新日: 2022/7/15
typoの修正くらいなら更新しなくてもいいかなと思ってましたが、この文書は一応翻訳も変えてるので更新しますね。
basic-operators.mdのほうはtypo修正だけなので更新しないでいいでしょうか。

2022-08-10 02:01 UTC, tsubasarc submitted a review, later dismissed

2022-08-10 06:51 UTC, stzn commented on language-guide/advanced-operators.md
> +最終更新日: 2022/7/15
ありがとうございますmm

> basic-operators.mdのほうはtypo修正だけなので更新しないでいいでしょうか。

はい、内容の変更がないのでいらないと思います。

2022-08-10 12:00 UTC, t-ae commented on language-guide/advanced-operators.md
> +最終更新日: 2022/7/15
更新しました。

2022-08-10 12:55 UTC, stzn approved these changes
ありがとうございます！

2022-08-12 02:34 UTC, tsubasarc requested changes

2022-08-12 02:34 UTC, tsubasarc commented on language-guide/advanced-operators.md
> +最終更新日: 2022/8/10
```suggestion
最終更新日: 2022/8/10
```

2022-08-12 02:36 UTC, tsubasarc commented on language-guide/advanced-operators.md
> +最終更新日: 2022/8/10
間違えてスペースが入ったのではと思うのですが、確認お願いします 🙇🏽

2022-08-12 02:42 UTC, t-ae commented on language-guide/advanced-operators.md
> +最終更新日: 2022/8/10
これは改行のためのスペースです。
抜けていたので修正しました。
他のドキュメントもこの行はスペースで改行していますが、誤って消しやすいので全部二重改行に置き換えてもいいかもしれませんね。@stzn

2022-08-12 02:56 UTC, tsubasarc commented on language-guide/advanced-operators.md
> +最終更新日: 2022/8/10
そうだったんですね。失礼しました！

僕が触ったファイルはこの箇所のスペースを消してしまっていると思います。
例えばよく知られている事柄に対して単なる己の無知が原因かも知れないですし、このままスペースを使う改行方法でいいと思いますが、方法をどうするかは @stzn さんからも何か意見を聞けたらと思います。

2022-08-12 02:57 UTC, tsubasarc approved these changes

2022-08-12 04:33 UTC, stzn commented on language-guide/advanced-operators.md
> +最終更新日: 2022/8/10
>他のドキュメントもこの行はスペースで改行していますが、誤って消しやすいので全部二重改行に置き換えてもいいかもしれませんね。

そうですね。markdownのこの改行方法はわかりづらいので、二重改行に置き換えが良いような気がします👍🏻
これは別issueで対応しましょう！

2022-08-12 04:35 UTC, stzn commented on language-guide/advanced-operators.md
> +最終更新日: 2022/8/10
https://github.com/stzn/the-swift-programming-language-jp/issues/341

2022-08-12 04:36 UTC, merged